### ISSUE TITLE
Maybe update License to GPL v3

### ISSUE THREAD

**Issue by richaber** [BenjaminLawson/PDF.js-Viewer-Shortcode#3]
Hello @BenjaminLawson,

@TwisterMc asked me to have a look at his fork of this project, as he would like to have me potentially write a Gutenberg block for it.

In perusing, I have noticed that the plugin’s header block says the license is `GPL v2`, but the repo includes an `Apache v2` LICENSE file in the root.

Initially I thought the LICENSE file in the root should be changed to `GPL v2`, since this is a WordPress (`GPL v2`) derivative work, and it is stated that the plugin is `GPL v2` in the plugin header.

However, Mozilla’s PDF.js lib is licensed as `Apache v2`, which, as I understand it, is not *directly* compatible with `GPL v2`.

Based on my reading of [this post](https://make.wordpress.org/themes/2013/03/04/licensing-note-apache-and-gpl/) on Make by the Theme Review Team, the plugin license should *probably* be updated to `GPL v3` in both the LICENSE file and the plugin header, to make it compatible with both WordPress’ own `GPL v2` license, and PDF.js’ `Apache v2` license.

**Comment by BenjaminLawson** [comment]
Done, thanks.
