### ISSUE TITLE
Update Minimum PHP version?

### ISSUE THREAD

**Issue by richaber** [BenjaminLawson/PDF.js-Viewer-Shortcode#4]
Hello @BenjaminLawson,

@TwisterMc asked me to have a look at his fork of this project, as he would like to have me potentially write a Gutenberg block for it.

WordPress bumped their [minimum PHP requirement to 5.6](https://wptavern.com/wordpress-ends-support-for-php-5-2-5-5-bumps-minimum-required-php-version-to-5-6), and they are currently planning to bump the minimum PHP requirement again, to PHP 7, possibly by end of year.

I am curious if you are okay with bumping the minimum PHP version for this project to 5.6, or 7?

**Comment by BenjaminLawson** [comment]
Sounds good to me!
